twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        allCategories: '@App\Repository\CategoryRepository'
        allPrograms: '@App\Repository\ProgramRepository'
        allActors: '@App\Repository\ActorRepository'

when@test:
    twig:
        strict_variables: true
